#!/usr/bin/env bash

set -ef

declare -r program=${BASH_SOURCE[0]}

usage() {
  cat <<EOF
Usage: ${program} [<kernel_build_dir>] [options]

  <kernel_build_dir>
  The kernel build directory.

  --? | --help
  Print this message and exit.

  --no-module
  Do not install modules.

  --no-boot
  Do not install boot.

  --no-loader-conf
  Do not install the systemd-boot loader config.

  --remove
  Remove the linux package kernel from boot.
EOF
  exit "${1:-2}"
}

parse_parameters() {
  local -a arguments

  no_module=0
  no_boot=0
  no_loader_conf=0
  remove=0

  while [[ $# -gt 0 ]]; do
    local -l option="${1/#--/-}"

    case "${option}" in
    -\? | -h | -he | -hel | -help)
      usage 0
      ;;
    -no-m | -no-mo | -no-mod | -no-modu | -no-modul | -no-module)
      no_module=1
      ;;
    -no-b | -no-bo | -no-boo | -no-boot)
      no_boot=1
      ;;
    -no-l | -no-lo | -no-loa | -no-load | -no-loade | -no-loader | -no-loader- | -no-loader-c | -no-loader-co | -no-loader-con | -no-loader-conf)
      no_loader_conf=1
      ;;
    -r | -re | -rem | -remo | -remov | -remove)
      remove=1
      ;;
    -*)
      echo "Unknown option: $1"
      usage
      ;;
    *)
      arguments+=("$1")
      ;;
    esac

    shift
  done

  kernel_build_dir=${arguments[0]}

  if [[ -z ${kernel_build_dir} && no_module -eq 0 && remove -eq 0 ]]; then
    echo "Missing value for argument: <kernel_build_dir>"
    usage
  fi
}

parse_parameters "$@"

declare -r remove
declare -r kernel_build_dir
declare -r no_module
declare -r no_boot
declare -r machine_id=c926b349fcb441b28056b1018c44552d
root_uuid=$(findmnt --mountpoint / --output UUID --noheadings)
declare -r root_uuid

# shellcheck disable=SC2207
if info=($(pacman -Q linux 2>/dev/null)); then
  declare -r package_version="${info[1]%'.'*}-${info[1]##*'.'}"
  declare -r package_image_name=/usr/lib/modules/"${package_version}"/vmlinuz
  unset info
fi

if [[ remove -eq 1 ]]; then
  if [[ -z ${package_version} ]]; then
    echo "Failed to determine linux package version!"
    echo "Removing nothing..."
    exit 1
  fi
  rm /boot/loader/entries/"${machine_id}"-"${package_version}".conf
  rm -r /boot/"${machine_id:?}"/"${package_version}"
  exit 0
fi

install_boot() {
  install -D "${image_name}" /boot/"${machine_id}"/"${version}"/linux
  install -D <(
    cat <<EOF
title      Arch Linux (${version})
sort-key   arch
version    ${version}
machine-id ${machine_id}
linux      /${machine_id}/${version}/linux
initrd     /${machine_id}/${version}/initrd
options    root=UUID=${root_uuid} rw quiet
EOF
  ) /boot/loader/entries/"${machine_id}"-"${version}".conf
  mkinitcpio --kernel "${version}" --generate /boot/"${machine_id}"/"${version}"/initrd
}

if [[ -n ${kernel_build_dir} ]]; then
  version=$(make -f "${kernel_build_dir}"/Makefile -s kernelrelease)
  image_name="${kernel_build_dir}/$(make -f "${kernel_build_dir}"/Makefile -s image_name)"
  declare -r modules_dir=/usr/lib/modules/"${version}"

  if [[ no_module -eq 0 ]]; then
    install -Dm644 "${image_name}" "${modules_dir}"/vmlinuz
    ZSTD_CLEVEL=19 make -j -f "${kernel_build_dir}"/Makefile modules_install \
      INSTALL_MOD_PATH=/usr INSTALL_MOD_STRIP=1
    rm "${modules_dir}"/build
  fi

  if [[ no_boot -eq 0 ]]; then
    install_boot
  fi
fi

if [[ no_boot -eq 0 ]]; then
  if [[ -n ${package_version} ]]; then
    version="${package_version}"
    image_name="${package_image_name}"
    install_boot
  fi

  if [[ no_loader_conf -eq 0 ]]; then
    install -D <(
      cat <<EOF
timeout 20
default ${machine_id}-*
EOF
    ) /boot/loader/loader.conf
  fi
fi
