#!/usr/bin/env bash

set -ef

declare -r program=${BASH_SOURCE[0]}

usage() {
  cat <<EOF
Usage: ${program} [<kernel_build_dir>] [options]

  <kernel_build_dir>
  The kernel build directory.

  --? | --help
  Print this message and exit.

  --no-module
  Do not install modules.

  --no-boot
  Do not install boot.

  --no-loader-conf
  Do not install the systemd-boot loader config.

  --remove [<version>]
  Remove the specified <version>, or pacman installed version, from boot and modules.
  The options --no-module and --no-boot have the expected effect.
EOF
  exit "${1:-2}"
}

parse_parameters() {
  local -a remove_args
  local -a freeform_args
  local -n args_ref=freeform_args

  no_module=0
  no_boot=0
  no_loader_conf=0
  remove=0

  while [[ $# -gt 0 ]]; do
    local -l option="${1/#--/-}"

    case "${option}" in
    -\? | -h | -he | -hel | -help)
      usage 0
      ;;
    -no-m | -no-mo | -no-mod | -no-modu | -no-modul | -no-module)
      no_module=1
      ;;
    -no-b | -no-bo | -no-boo | -no-boot)
      no_boot=1
      ;;
    -no-l | -no-lo | -no-loa | -no-load | -no-loade | -no-loader | -no-loader- | -no-loader-c | -no-loader-co | -no-loader-con | -no-loader-conf)
      no_loader_conf=1
      ;;
    -r | -re | -rem | -remo | -remov | -remove)
      remove=1
      local -n args_ref=remove_args
      ;;
    -*)
      echo "Unknown option: $1"
      usage
      ;;
    *)
      args_ref+=("$1")
      # shellcheck disable=SC2178
      local -n args_ref=freeform_args
      ;;
    esac

    shift
  done

  kernel_build_dir="${freeform_args[0]}"
  makefile="${kernel_build_dir}"/Makefile
  version="${remove_args[0]}"

  # shellcheck disable=SC2207
  if [[ -n ${kernel_build_dir} ]]; then
    version=$(make -f "${makefile}" -s kernelrelease)
    image_name="${kernel_build_dir}/$(make -f "${makefile}" -s image_name)"
  elif [[ -n ${version} ]]; then
    image_name=/usr/lib/modules/"${version}"/vmlinuz
  elif info=($(pacman -Q linux 2>/dev/null)); then
    version="${info[1]%.*}-${info[1]##*.}"
    image_name=/usr/lib/modules/"${version}"/vmlinuz
    unset info
  fi

  if [[ -z ${version} ]]; then
    echo "Failed to determine version!"
    usage
  fi
}

parse_parameters "$@"

declare -r no_module
declare -r no_boot
declare -r no_loader_conf
declare -r remove
declare -r version
declare -r image_name
declare -r modules_dir=/usr/lib/modules/"${version:?}"
declare -r machine_id=c926b349fcb441b28056b1018c44552d
declare -r kernel_build_dir
declare -r makefile

if [[ remove -eq 1 ]]; then
  if [[ no_module -eq 0 ]]; then
    rm -r "${modules_dir}"
  fi
  if [[ no_boot -eq 0 ]]; then
    rm /boot/loader/entries/"${machine_id}"-"${version}".conf
    rm -r /boot/"${machine_id:?}"/"${version}"
  fi
  exit 0
fi

install_boot() {
  install -D "${image_name}" /boot/"${machine_id}"/"${version}"/linux

  install -D <(
    cat <<EOF
title      Arch Linux (${version})
sort-key   arch
version    ${version}
machine-id ${machine_id}
linux      /${machine_id}/${version}/linux
initrd     /${machine_id}/${version}/initrd
options    root=UUID=${root_uuid} rw quiet
EOF
  ) /boot/loader/entries/"${machine_id}"-"${version}".conf

  if [[ no_loader_conf -eq 0 ]]; then
    install -D <(
      cat <<EOF
timeout 20
default ${machine_id}-*
EOF
    ) /boot/loader/loader.conf
  fi

  mkinitcpio --kernel "${version}" --generate /boot/"${machine_id}"/"${version}"/initrd
}

root_uuid=$(findmnt --mountpoint / --output UUID --noheadings)
declare -r root_uuid

if [[ -n ${kernel_build_dir} ]]; then
  if [[ no_module -eq 0 ]]; then
    install -D -m 644 "${image_name}" "${modules_dir}"/vmlinuz
    ZSTD_CLEVEL=19 make -j -f "${makefile}" modules_install INSTALL_MOD_PATH=/usr INSTALL_MOD_STRIP=1
    rm "${modules_dir}"/build
  fi

  if [[ no_boot -eq 0 ]]; then
    install_boot
  fi

  exit 0
fi

if [[ no_boot -eq 0 ]]; then
  install_boot
fi
