# man 5 pacman.conf

[options]
HoldPkg = pacman glibc
Architecture = auto
IgnorePkg = sudo neovim
NoExtract = boot/*
CheckSpace
ParallelDownloads = 5
DownloadUser = alpm
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist
