animations {
  enabled = false
}

background {
  path = ~/Pictures/day.png
}

input-field {
  fade_on_empty = false
  size = 20%, 5%
  rounding = 0
  halign = center
  valign = center
  placeholder_text = <i>Password</i>
}

label {
  text = cmd[update:1000] echo "$TIME"
  halign = right
  valign = bottom
  position = -40, 25
}
