animations {
  enabled = false
}

background {
  path = ~/Pictures/day.png
  blur_passes = 2
  blur_size = 4
}

input-field {
  size = 20%, 5%
  halign = center
  valign = center
  inner_color = rgb(239,241,245)
  outer_color = rgb(76,79,105)
  font_color = rgb(76,79,105)
  check_color = rgb(114,135,253)
  outline_thickness = 4
  font_family = JetBrains Mono NL
  placeholder_text = Enter Password
  fail_text = <i>$FAIL ($ATTEMPTS)</i>
  rounding = 10
  fade_on_empty = false
}

label {
  text = cmd[update:200] echo "<span background='##02061880' line_height='2' font_weight='bold'>  $(date)  </span>"
  halign = center
  valign = center
  position = 0, 8%
  font_size = 26
  font_family = JetBrains Mono NL
}
