animations {
  enabled = false
}

background {
  path = ~/Pictures/day.png
  blur_passes = 2
  blur_size = 4
}

input-field {
  size = 20%, 5%
  halign = center
  valign = center
  font_family = JetBrains Mono NL
  placeholder_text = Enter Password
  fail_text = <i>$FAIL ($ATTEMPTS)</i>
  fade_on_empty = false
  outline_thickness = 2
  rounding = 0
  dots_size = 0.2
  dots_spacing = 0.2
  inner_color = rgba(2,6,24,0.25)
  font_color = rgb(244,244,244)
  check_color = rgb(116,212,255)
  fail_color = rgb(254,249,194)
  outer_color = rgba(248,250,252,0.8)
}

label {
  text = cmd[update:200] echo "<span background='##02061880' line_height='2' font_weight='bold'>  $(date)  </span>"
  halign = center
  valign = center
  position = 0, 8%
  font_size = 26
  font_family = JetBrains Mono NL
}
